/** Offline integration fixture. This verifies the harness, never real coaching quality. */
import { Usage } from '@openai/agents';
import {
  ScriptedModel,
  assistantMessage,
  functionCall,
  modelResponse,
} from '@openai/agents/testing';
import type { Scenario } from './scenario.js';
import { addDays } from './scenario.js';
import type { BenchmarkSnapshot } from '@askesis/api/benchmark';
import type { Review } from './models.js';
import { criteria } from './models.js';

export function scriptedCoach(scenario: Scenario) {
  const reply = (text: string) =>
    modelResponse({ usage: new Usage(), output: [assistantMessage(text)] });
  const call = (name: string, input: Record<string, unknown>) =>
    modelResponse({
      usage: new Usage(),
      output: [functionCall(name, input, { callId: `scripted-${name}` })],
    });
  const weeks = Array.from({ length: 4 }, (_, i) => ({
    key: `week-${i}`,
    blockKey: 'base',
    title: `Week ${i + 1}`,
    description: null,
    startDate: addDays(scenario.dates.startDate, i * 7),
    endDate: addDays(scenario.dates.startDate, i * 7 + 6),
    position: i + 1,
    weekNumber: i + 1,
    cutback: i === 3,
  }));
  return new ScriptedModel([
    reply(
      'Please share your goal, dates, training history, available days, recent race result and preferred planning horizon.',
    ),
    call('create_plan_draft', {
      displayName: 'Scripted benchmark half marathon',
      startDate: scenario.dates.startDate,
      endDate: scenario.dates.eventDate,
    }),
    call('record_performance', {
      system: 'run_pace',
      input: { method: 'race_result', distanceMetres: 5000, durationSeconds: 1680 },
      provenance: 'user_supplied',
      observedOn: scenario.dates.observedOn,
      estimateBasis: 'Athlete reported a fair-condition all-out 5 km race.',
    }),
    call('update_plan_brief', {
      startDate: scenario.dates.startDate,
      endDate: scenario.dates.eventDate,
      description: 'First four weeks of a twelve-week half-marathon goal.',
      brief: {
        goal: 'Finish my first half marathon comfortably.',
        unit: 'kilometres',
        context: 'Only Tuesday, Thursday and Sunday; prescribe the first four weeks now.',
        sports: [
          {
            sport: 'run',
            currentSessions: { status: 'known', value: 3 },
            desiredSessions: 3,
            weeklyDistance: { status: 'known', value: 22000 },
            longestDistance: { status: 'known', value: 9000 },
          },
        ],
        weekdays: [
          'unavailable',
          'available',
          'unavailable',
          'available',
          'unavailable',
          'unavailable',
          'preferred',
        ],
      },
    }),
    call('apply_schedule_changes', {
      generation: { startDate: scenario.dates.startDate, endDate: scenario.dates.coverageEndDate },
      coverage: { startDate: scenario.dates.startDate, endDate: scenario.dates.coverageEndDate },
      blocks: [
        {
          key: 'base',
          title: 'Aerobic foundation',
          description: null,
          phase: 'base',
          startDate: scenario.dates.startDate,
          endDate: scenario.dates.coverageEndDate,
          position: 1,
        },
      ],
      weeks,
      workouts: weeks.flatMap((week, index) =>
        [1, 3, 6].map((offset, day) => ({
          key: `run-${index}-${day}`,
          weekKey: week.key,
          date: addDays(week.startDate, offset),
          position: 1,
          discipline: 'run',
          title: day === 2 ? 'Easy long run' : 'Easy run',
          description: null,
          purpose: 'Develop aerobic endurance.',
          priority: 'medium',
          racePriority: null,
          estimatedDurationSeconds: day === 2 ? 3600 : 2400,
          estimatedDistanceMetres: [5000, 6000, 9000][day]!,
          tags: [],
          steps: [
            {
              parentIndex: null,
              kind: 'effort',
              repeatCount: null,
              role: 'work',
              label: 'Easy running',
              instructions: 'Keep the effort comfortable.',
              completion: { type: 'distance', value: [5000, 6000, 9000][day]!, unit: 'metres' },
              targets: [{ type: 'zone', key: 'easy' }],
            },
          ],
        })),
      ),
      deleteWorkoutIds: [],
      deleteWeekIds: [],
      deleteBlockIds: [],
    }),
    call('validate_plan', {}),
    reply(
      'The first four weeks are saved. This response was generated by an offline scripted fixture.',
    ),
  ]);
}

export function scriptedReview(snapshot: BenchmarkSnapshot): Review {
  return {
    verdict: 'needs_revision',
    summary:
      'Offline fixture verifies persistence and report wiring. It does not assess model quality.',
    criteria: criteria.map((criterion) => ({
      criterion,
      result: 'uncertain',
      explanation: 'No live reviewer ran.',
      evidence: snapshot.messages.length
        ? [`message:${snapshot.messages[0]!.sequence}`]
        : ['plan:brief'],
    })),
  };
}
