/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    planVersionId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Scheduled workouts in chronological order. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutList"];
                    };
                };
                /** @description Authentication is required. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{workoutId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workoutId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A workout and its nested prescription tree. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutDetail"];
                    };
                };
                /** @description Authentication is required. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Workout not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            revisions: {
                                id: string;
                                /** @enum {string} */
                                state: "locked";
                                versionNumber: number;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                                contentHash: string;
                                contentSchemaVersion: number;
                                validatorVersion: number;
                                findings: {
                                    code: string;
                                    /** @enum {string} */
                                    severity: "error" | "warning";
                                    message: string;
                                    path: string;
                                }[];
                                acknowledgedWarningCodes: string[];
                                summary: {
                                    headerChanges: string[];
                                    entities: {
                                        [key: string]: {
                                            added: number;
                                            changed: number;
                                            removed: number;
                                        };
                                    };
                                };
                            }[];
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                    revisionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            revision: {
                                id: string;
                                /** @enum {string} */
                                state: "locked";
                                versionNumber: number;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                                contentHash: string;
                                contentSchemaVersion: number;
                                validatorVersion: number;
                                findings: {
                                    code: string;
                                    /** @enum {string} */
                                    severity: "error" | "warning";
                                    message: string;
                                    path: string;
                                }[];
                                acknowledgedWarningCodes: string[];
                                summary: {
                                    headerChanges: string[];
                                    entities: {
                                        [key: string]: {
                                            added: number;
                                            changed: number;
                                            removed: number;
                                        };
                                    };
                                };
                            };
                            content: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/revisions/{revisionId}/restore-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                    revisionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sourceRevisionId: string;
                            currentVersionId: string;
                            stateVersion: number;
                            sourceHash: string;
                            summary: {
                                headerChanges: string[];
                                entities: {
                                    [key: string]: {
                                        added: number;
                                        changed: number;
                                        removed: number;
                                    };
                                };
                            };
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/revisions/{revisionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "idempotency-key": string;
                };
                path: {
                    planId: string;
                    revisionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedStateVersion: number;
                        expectedCurrentVersionId: string;
                        expectedSourceHash: string;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        displayName: string;
                        expectedStateVersion: number;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/plans/{planId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedStateVersion: number;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedStateVersion: number;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedStateVersion: number;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedStateVersion: number;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    collection?: "library" | "active" | "archive";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plans: {
                                id: string;
                                displayName: string;
                                stateVersion: number;
                                active: boolean;
                                archived: boolean;
                                draft: {
                                    id: string;
                                    /** @enum {string} */
                                    state: "draft" | "locked";
                                    versionNumber: number | null;
                                    editNumber: number;
                                    description: string | null;
                                    /** Format: date */
                                    startDate: string | null;
                                    /** Format: date */
                                    endDate: string | null;
                                    basedOnVersionId: string | null;
                                    supersedesVersionId: string | null;
                                    lockedAt: string | null;
                                } | null;
                                locked: {
                                    id: string;
                                    /** @enum {string} */
                                    state: "draft" | "locked";
                                    versionNumber: number | null;
                                    editNumber: number;
                                    description: string | null;
                                    /** Format: date */
                                    startDate: string | null;
                                    /** Format: date */
                                    endDate: string | null;
                                    basedOnVersionId: string | null;
                                    supersedesVersionId: string | null;
                                    lockedAt: string | null;
                                } | null;
                            }[];
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "idempotency-key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        displayName: string;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedDraftId: string;
                        expectedEditNumber: number;
                        description: string | null;
                        /** Format: date */
                        startDate: string | null;
                        /** Format: date */
                        endDate: string | null;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/plans/{planId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            draftId: string;
                            editNumber: number;
                            stateVersion: number;
                            contentHash: string;
                            validationDigest: string;
                            findings: {
                                code: string;
                                /** @enum {string} */
                                severity: "error" | "warning";
                                message: string;
                                path: string;
                            }[];
                            hasChanges: boolean;
                            summary: {
                                headerChanges: string[];
                                entities: {
                                    [key: string]: {
                                        added: number;
                                        changed: number;
                                        removed: number;
                                    };
                                };
                            };
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedStateVersion: number;
                        expectedDraftId?: string;
                        expectedEditNumber?: number;
                        expectedContentHash?: string;
                        expectedValidationDigest?: string;
                        acknowledgedWarningCodes?: string[];
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "idempotency-key": string;
                };
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedStateVersion: number;
                        expectedDraftId?: string;
                        expectedEditNumber?: number;
                        expectedContentHash?: string;
                        expectedValidationDigest?: string;
                        acknowledgedWarningCodes?: string[];
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "idempotency-key": string;
                };
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedStateVersion: number;
                        expectedDraftId?: string;
                        expectedEditNumber?: number;
                        expectedContentHash?: string;
                        expectedValidationDigest?: string;
                        acknowledgedWarningCodes?: string[];
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            displayName: string;
                            stateVersion: number;
                            active: boolean;
                            archived: boolean;
                            draft: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                            locked: {
                                id: string;
                                /** @enum {string} */
                                state: "draft" | "locked";
                                versionNumber: number | null;
                                editNumber: number;
                                description: string | null;
                                /** Format: date */
                                startDate: string | null;
                                /** Format: date */
                                endDate: string | null;
                                basedOnVersionId: string | null;
                                supersedesVersionId: string | null;
                                lockedAt: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Request rejected. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Request rejected. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkoutList: {
            workouts: components["schemas"]["WorkoutSummary"][];
        };
        WorkoutSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            planId: string;
            /** Format: uuid */
            planVersionId: string;
            planTitle: string;
            weekNumber: number;
            /** Format: date */
            scheduledDate: string;
            title: string;
            description: string | null;
            purpose: string | null;
            discipline: string;
            priority: components["schemas"]["WorkoutPriority"];
            estimatedDurationSeconds: number | null;
            estimatedDistanceMetres: number | null;
        };
        /** @enum {string} */
        WorkoutPriority: "low" | "medium" | "high";
        Error: {
            error: {
                code: string;
                message: string;
                requestId: string;
            };
        };
        WorkoutDetail: {
            workout: components["schemas"]["WorkoutSummary"];
            tags: string[];
            prescription: components["schemas"]["WorkoutStep"];
        };
        WorkoutStep: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["WorkoutStepKind"];
            role: string | null;
            discipline: string | null;
            repeatCount: number | null;
            label: string | null;
            instructions: string | null;
            movement: {
                /** Format: uuid */
                id: string;
                name: string;
                category: string;
            } | null;
            completion: components["schemas"]["StepCompletion"];
            targets: components["schemas"]["StepTarget"][];
            steps: components["schemas"]["WorkoutStep"][];
        };
        /** @enum {string} */
        WorkoutStepKind: "sequence" | "repeat" | "effort";
        StepCompletion: {
            /** @enum {string} */
            type: "duration" | "distance" | "repetitions" | "energy" | "until_lap" | "until_condition" | "open";
            value: number | null;
            unit: string | null;
            conditionType: string | null;
            conditionValue: string | null;
        } | null;
        StepTarget: {
            /** @enum {string} */
            type: "zone" | "pace" | "speed" | "heart_rate" | "power" | "cadence" | "rpe" | "load" | "percentage_1rm" | "rir" | "tempo" | "instruction";
            minimumValue: number | null;
            targetValue: number | null;
            maximumValue: number | null;
            unit: string | null;
            zoneSystem: string | null;
            zoneKey: string | null;
            text: string | null;
            resolvedZone: components["schemas"]["ResolvedZone"];
        };
        ResolvedZone: {
            /** Format: uuid */
            profileId: string;
            method: string;
            fitnessValue: number | null;
            metric: string;
            minimumValue: number | null;
            targetValue: number | null;
            maximumValue: number | null;
            unit: string;
        } | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
