/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AthleteIdentities {
  athlete_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  provider: string;
  provider_subject: string;
}

export interface Athletes {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AtlasSchemaRevisionsAtlasSchemaRevisions {
  applied: Generated<Int8>;
  description: string;
  error: string | null;
  error_stmt: string | null;
  executed_at: Timestamp;
  execution_time: Int8;
  hash: string;
  operator_version: string;
  partial_hashes: Json | null;
  total: Generated<Int8>;
  type: Generated<Int8>;
  version: string;
}

export interface CalibrationProfiles {
  created_at: Generated<Timestamp>;
  discipline: string;
  fitness_value: Numeric | null;
  id: Generated<string>;
  method: string;
  owner_id: string;
  source_description: string | null;
  system: string;
}

export interface CalibrationZones {
  id: Generated<string>;
  maximum_value: Numeric | null;
  metric: string;
  minimum_value: Numeric | null;
  profile_id: string;
  target_value: Numeric | null;
  unit: string;
  zone_key: string;
}

export interface Movements {
  category: string;
  id: Generated<string>;
  instructions: string | null;
  name: string;
  primary_discipline: Generated<string>;
}

export interface PlanCalibrationPeriods {
  effective_from: Timestamp;
  effective_until: Timestamp | null;
  id: Generated<string>;
  plan_id: string;
  profile_id: string;
  system: string;
}

export interface PlanConstraints {
  constraint_type: string;
  day_of_week: number | null;
  description: string | null;
  discipline: string | null;
  id: Generated<string>;
  numeric_value: Numeric | null;
  plan_id: string;
  severity: string;
  unit: string | null;
}

export interface PlanGoals {
  description: string | null;
  discipline: string | null;
  distance_unit: string | null;
  distance_value: Numeric | null;
  event_date: Timestamp | null;
  event_name: string | null;
  goal_type: string;
  id: Generated<string>;
  plan_id: string;
  priority: string;
  target_duration_seconds: number | null;
}

export interface PlanMemberships {
  athlete_id: string;
  created_at: Generated<Timestamp>;
  plan_id: string;
  role: string;
}

export interface Plans {
  created_at: Generated<Timestamp>;
  description: string | null;
  end_date: Timestamp;
  id: Generated<string>;
  owner_id: string;
  schema_version: Generated<number>;
  slug: string;
  start_date: Timestamp;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface SeedRuns {
  applied_at: Generated<Timestamp>;
  seed_key: string;
}

export interface StepCompletions {
  completion_type: string;
  condition_type: string | null;
  condition_value: string | null;
  numeric_value: Numeric | null;
  step_id: string;
  unit: string | null;
}

export interface StepTargets {
  id: Generated<string>;
  maximum_value: Numeric | null;
  minimum_value: Numeric | null;
  position: number;
  step_id: string;
  target_type: string;
  target_value: Numeric | null;
  text_value: string | null;
  unit: string | null;
  zone_key: string | null;
  zone_system: string | null;
}

export interface TrainingBlocks {
  description: string | null;
  end_date: Timestamp;
  id: Generated<string>;
  plan_id: string;
  position: number;
  start_date: Timestamp;
  title: string;
}

export interface TrainingWeeks {
  block_id: string;
  description: string | null;
  end_date: Timestamp;
  id: Generated<string>;
  plan_id: string;
  position: number;
  start_date: Timestamp;
  title: string;
  week_number: number;
}

export interface WeeklyPlanSummary {
  end_date: Timestamp | null;
  estimated_cycle_distance_metres: Numeric | null;
  estimated_duration_seconds: Int8 | null;
  estimated_run_distance_metres: Numeric | null;
  estimated_swim_distance_metres: Numeric | null;
  plan_id: string | null;
  start_date: Timestamp | null;
  title: string | null;
  week_id: string | null;
  week_number: number | null;
  workout_count: Int8 | null;
}

export interface WeekTargets {
  discipline: string | null;
  id: Generated<string>;
  maximum_value: Numeric | null;
  metric: string;
  minimum_value: Numeric | null;
  target_value: Numeric | null;
  unit: string;
  week_id: string;
}

export interface WorkoutPrescriptionTotals {
  discipline: string | null;
  distance_metres: Numeric | null;
  duration_seconds: Numeric | null;
  repetitions: Numeric | null;
  workout_id: string | null;
}

export interface Workouts {
  created_at: Generated<Timestamp>;
  description: string | null;
  estimated_distance_metres: Numeric | null;
  estimated_duration_seconds: number | null;
  id: Generated<string>;
  plan_id: string;
  position: number;
  primary_discipline: string;
  priority: Generated<string>;
  purpose: string | null;
  scheduled_date: Timestamp;
  title: string;
  updated_at: Generated<Timestamp>;
  week_id: string;
}

export interface WorkoutSteps {
  discipline: string | null;
  id: Generated<string>;
  instructions: string | null;
  kind: string;
  label: string | null;
  movement_id: string | null;
  parent_step_id: string | null;
  position: number;
  repeat_count: number | null;
  role: string | null;
  workout_id: string;
}

export interface WorkoutTags {
  tag: string;
  workout_id: string;
}

export interface DB {
  athlete_identities: AthleteIdentities;
  athletes: Athletes;
  "atlas_schema_revisions.atlas_schema_revisions": AtlasSchemaRevisionsAtlasSchemaRevisions;
  calibration_profiles: CalibrationProfiles;
  calibration_zones: CalibrationZones;
  movements: Movements;
  plan_calibration_periods: PlanCalibrationPeriods;
  plan_constraints: PlanConstraints;
  plan_goals: PlanGoals;
  plan_memberships: PlanMemberships;
  plans: Plans;
  seed_runs: SeedRuns;
  step_completions: StepCompletions;
  step_targets: StepTargets;
  training_blocks: TrainingBlocks;
  training_weeks: TrainingWeeks;
  week_targets: WeekTargets;
  weekly_plan_summary: WeeklyPlanSummary;
  workout_prescription_totals: WorkoutPrescriptionTotals;
  workout_steps: WorkoutSteps;
  workout_tags: WorkoutTags;
  workouts: Workouts;
}
