/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AgentProgressBatches {
  input_hash: string;
  run_id: string;
  sequence: number;
}

export interface AgentRunEvents {
  created_at: Generated<Timestamp>;
  metadata: Generated<Json>;
  run_id: string;
  sequence: number;
  type: string;
}

export interface AgentRunFinishes {
  input_hash: string;
  run_id: string;
  status: string;
}

export interface AgentRunMeasurements {
  run_id: string;
  timings: Generated<Json>;
}

export interface AgentRunOutputs {
  content: Generated<string>;
  is_final: Generated<boolean>;
  item_id: string;
  position: number;
  revision: number;
  run_id: string;
  truncated: Generated<boolean>;
}

export interface AgentRuns {
  cancel_requested_at: Timestamp | null;
  context: Json | null;
  conversation_id: string;
  cost_amount: Numeric | null;
  cost_currency: string | null;
  created_at: Generated<Timestamp>;
  credential_digest: string | null;
  deadline_at: Generated<Timestamp>;
  execution_edit_number: number | null;
  execution_plan_id: string | null;
  execution_version_id: string | null;
  failure_code: string | null;
  finished_at: Timestamp | null;
  generation_end_date: Timestamp | null;
  generation_prescribed_through: Timestamp | null;
  generation_start_date: Timestamp | null;
  id: Generated<string>;
  input_tokens: number | null;
  lease_expires_at: Timestamp | null;
  lease_generation: Generated<number>;
  model: string | null;
  output_tokens: number | null;
  owner_id: string;
  plan_id: string | null;
  prompt_version: string | null;
  provider: string | null;
  reasoning: string | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  tool_count: Generated<number>;
  user_message_id: string;
  worker_id: string | null;
}

export interface AgentToolChanges {
  operation_id: string;
  run_id: string;
  summary: Json;
}

export interface AgentToolReceipts {
  created_at: Generated<Timestamp>;
  edit_number: number | null;
  input_hash: string;
  operation_id: string;
  response: Json;
  run_id: string;
  target_version_id: string | null;
  tool_name: string;
}

export interface AgentWorkers {
  id: string;
  last_seen_at: Generated<Timestamp>;
  model: string;
  prompt_version: string;
  provider: string;
  ready: Generated<boolean>;
  reasoning: string;
}

export interface ApiIdempotencyKeys {
  athlete_id: string;
  command_scope: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string;
  request_hash: string;
  response_body: Json;
  response_status: number;
}

export interface AthleteCalibrations {
  athlete_id: string;
  calculator_version: string;
  effective_from: Timestamp;
  estimate_basis: string | null;
  fitness_value: Numeric | null;
  id: Generated<string>;
  input: Json;
  method: string;
  observed_on: Timestamp | null;
  provenance: string;
  recorded_at: Generated<Timestamp>;
  recorded_by_run_id: string | null;
  retracted_at: Timestamp | null;
  retracted_by_run_id: string | null;
  system: string;
}

export interface AthleteCalibrationZones {
  calibration_id: string;
  maximum_value: Numeric;
  metric: string;
  minimum_value: Numeric;
  target_value: Numeric;
  unit: string;
  zone_key: string;
}

export interface AthleteIdentities {
  athlete_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  provider: string;
  provider_subject: string;
}

export interface Athletes {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AtlasSchemaRevisionsAtlasSchemaRevisions {
  applied: Generated<Int8>;
  description: string;
  error: string | null;
  error_stmt: string | null;
  executed_at: Timestamp;
  execution_time: Int8;
  hash: string;
  operator_version: string;
  partial_hashes: Json | null;
  total: Generated<Int8>;
  type: Generated<Int8>;
  version: string;
}

export interface ConversationMessages {
  content: string;
  context: Json | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  producing_run_id: string | null;
  role: string;
  sequence: number;
}

export interface Conversations {
  activity_at: Generated<Timestamp>;
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  next_sequence: Generated<number>;
  owner_id: string;
  plan_id: string | null;
  state_version: Generated<number>;
  title: string;
}

export interface ExamplePlanEditions {
  anchor_date: Timestamp;
  blueprint_revision: string;
  created_at: Generated<Timestamp>;
  owner_id: string;
  plan_id: string;
  published_content_hash: string;
  published_state_version: number;
}

export interface LiveEventHeads {
  owner_id: string;
  sequence: Generated<Int8>;
}

export interface LiveEvents {
  created_at: Generated<Timestamp>;
  metadata: Json;
  owner_id: string;
  resource_id: string;
  sequence: Int8;
  transaction_id: Int8;
  type: string;
}

export interface MovementDefinitions {
  category: string;
  created_at: Generated<Timestamp>;
  definition_number: Generated<number>;
  id: Generated<string>;
  instructions: string | null;
  lineage_id: Generated<string>;
  name: string;
  primary_discipline: Generated<string>;
  supersedes_definition_id: string | null;
}

export interface PlanBriefs {
  acknowledged_warning_codes: string[] | null;
  confirmed_at: Timestamp | null;
  confirmed_edit_number: number | null;
  confirmed_hash: string | null;
  context: Generated<string>;
  distance_unit: Generated<string>;
  goal_text: Generated<string>;
  id: Generated<string>;
  lineage_id: Generated<string>;
  plan_version_id: string;
  schedule_review_required: Generated<boolean>;
  validator_version: number | null;
}

export interface PlanBriefSports {
  current_sessions_per_week: number | null;
  current_sessions_status: Generated<string>;
  desired_sessions_per_week: number | null;
  id: Generated<string>;
  lineage_id: Generated<string>;
  longest_session: Numeric | null;
  longest_session_status: string | null;
  plan_version_id: string;
  sport: string;
  weekly_volume: Numeric | null;
  weekly_volume_status: string | null;
}

export interface PlanBriefWeekdays {
  availability: string;
  id: Generated<string>;
  lineage_id: Generated<string>;
  plan_version_id: string;
  weekday: number;
}

export interface Plans {
  activated_at: Timestamp | null;
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_draft_version_id: string | null;
  current_locked_version_id: string | null;
  display_name: string;
  id: Generated<string>;
  owner_id: string;
  state_version: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface PlanScheduleCoverage {
  brief_hash: string;
  end_date: Timestamp;
  id: Generated<string>;
  lineage_id: Generated<string>;
  plan_version_id: string;
  start_date: Timestamp;
}

export interface PlanVersions {
  acknowledged_warning_codes: string[] | null;
  based_on_version_id: string | null;
  calibration_basis: Json | null;
  change_summary: Json | null;
  content_hash: string | null;
  content_hash_version: number | null;
  content_schema_version: Generated<number>;
  created_at: Generated<Timestamp>;
  description: string | null;
  edit_number: Generated<number>;
  end_date: Timestamp | null;
  id: Generated<string>;
  locked_at: Timestamp | null;
  plan_id: string;
  start_date: Timestamp | null;
  state: Generated<string>;
  supersedes_version_id: string | null;
  updated_at: Generated<Timestamp>;
  validation_findings: Json | null;
  validator_version: number | null;
  version_number: number | null;
}

export interface SeedRuns {
  applied_at: Generated<Timestamp>;
  seed_key: string;
}

export interface StepCompletions {
  completion_type: string;
  condition_type: string | null;
  condition_value: string | null;
  numeric_value: Numeric | null;
  plan_version_id: string;
  step_id: string;
  unit: string | null;
}

export interface StepTargets {
  id: Generated<string>;
  lineage_id: Generated<string>;
  maximum_value: Numeric | null;
  minimum_value: Numeric | null;
  plan_version_id: string;
  position: number;
  step_id: string;
  target_type: string;
  target_value: Numeric | null;
  text_value: string | null;
  unit: string | null;
  zone_key: string | null;
  zone_system: string | null;
}

export interface TrainingBlocks {
  description: string | null;
  end_date: Timestamp;
  id: Generated<string>;
  lineage_id: Generated<string>;
  phase: string | null;
  plan_version_id: string;
  position: number;
  start_date: Timestamp;
  title: string;
}

export interface TrainingWeeks {
  block_id: string;
  cutback: Generated<boolean>;
  description: string | null;
  end_date: Timestamp;
  id: Generated<string>;
  lineage_id: Generated<string>;
  plan_version_id: string;
  position: number;
  start_date: Timestamp;
  title: string;
  week_number: number;
}

export interface WeeklyPlanSummary {
  end_date: Timestamp | null;
  estimated_cycle_distance_metres: Numeric | null;
  estimated_duration_seconds: Int8 | null;
  estimated_run_distance_metres: Numeric | null;
  estimated_swim_distance_metres: Numeric | null;
  plan_version_id: string | null;
  start_date: Timestamp | null;
  title: string | null;
  week_id: string | null;
  week_number: number | null;
  workout_count: Int8 | null;
}

export interface WeekTargets {
  discipline: string | null;
  id: Generated<string>;
  lineage_id: Generated<string>;
  maximum_value: Numeric | null;
  metric: string;
  minimum_value: Numeric | null;
  plan_version_id: string;
  target_value: Numeric | null;
  unit: string;
  week_id: string;
}

export interface WorkoutPrescriptionTotals {
  discipline: string | null;
  distance_metres: Numeric | null;
  duration_seconds: Numeric | null;
  plan_version_id: string | null;
  repetitions: Numeric | null;
  workout_id: string | null;
}

export interface Workouts {
  created_at: Generated<Timestamp>;
  description: string | null;
  estimated_distance_metres: Numeric | null;
  estimated_duration_seconds: number | null;
  id: Generated<string>;
  lineage_id: Generated<string>;
  plan_version_id: string;
  position: number;
  primary_discipline: string;
  priority: Generated<string>;
  purpose: string | null;
  race_priority: string | null;
  scheduled_date: Timestamp;
  title: string;
  updated_at: Generated<Timestamp>;
  week_id: string;
}

export interface WorkoutSteps {
  discipline: string | null;
  id: Generated<string>;
  instructions: string | null;
  kind: string;
  label: string | null;
  lineage_id: Generated<string>;
  movement_id: string | null;
  parent_step_id: string | null;
  plan_version_id: string;
  position: number;
  repeat_count: number | null;
  role: string | null;
  workout_id: string;
}

export interface WorkoutTags {
  plan_version_id: string;
  tag: string;
  workout_id: string;
}

export interface DB {
  agent_progress_batches: AgentProgressBatches;
  agent_run_events: AgentRunEvents;
  agent_run_finishes: AgentRunFinishes;
  agent_run_measurements: AgentRunMeasurements;
  agent_run_outputs: AgentRunOutputs;
  agent_runs: AgentRuns;
  agent_tool_changes: AgentToolChanges;
  agent_tool_receipts: AgentToolReceipts;
  agent_workers: AgentWorkers;
  api_idempotency_keys: ApiIdempotencyKeys;
  athlete_calibration_zones: AthleteCalibrationZones;
  athlete_calibrations: AthleteCalibrations;
  athlete_identities: AthleteIdentities;
  athletes: Athletes;
  "atlas_schema_revisions.atlas_schema_revisions": AtlasSchemaRevisionsAtlasSchemaRevisions;
  conversation_messages: ConversationMessages;
  conversations: Conversations;
  example_plan_editions: ExamplePlanEditions;
  live_event_heads: LiveEventHeads;
  live_events: LiveEvents;
  movement_definitions: MovementDefinitions;
  plan_brief_sports: PlanBriefSports;
  plan_brief_weekdays: PlanBriefWeekdays;
  plan_briefs: PlanBriefs;
  plan_schedule_coverage: PlanScheduleCoverage;
  plan_versions: PlanVersions;
  plans: Plans;
  seed_runs: SeedRuns;
  step_completions: StepCompletions;
  step_targets: StepTargets;
  training_blocks: TrainingBlocks;
  training_weeks: TrainingWeeks;
  week_targets: WeekTargets;
  weekly_plan_summary: WeeklyPlanSummary;
  workout_prescription_totals: WorkoutPrescriptionTotals;
  workout_steps: WorkoutSteps;
  workout_tags: WorkoutTags;
  workouts: Workouts;
}
